version: "3.8"

services:
  init-db:
    image: docker:dind
    container_name: dbInit
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
    command: >
      sh -c "docker exec -i mainDB mysql -uroot -p'$DB_PASSWORD' -e 'CREATE DATABASE IF NOT EXISTS DB;'"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  "wp2.co-intel.com":
    image: wordpress
    container_name: "wp2.co-intel.com"
    restart: always
    depends_on:
      - init-db
    ports:
      - "8082:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ${DB_PASSWORD}
      WORDPRESS_DB_NAME: DB
    volumes:
      - "_data:/var/www/html"
    networks:
      - app-network

volumes:
  "_data": {}

networks:
  app-network:
    external: true
