version: '3.8'

services:

  db:
    image: mysql:8.0
    container_name: mainDB
    restart: always
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql:/var/lib/mysql
    networks:
      - app-network

volumes:
  mysql: {}

networks:
  app-network:
    external: true